=== cindy25-Collab/ByteMe/XML_Cursos/Cursos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="DNIType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[A-Za-z]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="IDType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="cursos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Horario" type="xs:string"/>
                            <xs:element name="idioma" type="xs:string"/>
                            <xs:element name="NivelDificultad" type="xs:string"/>
                            <xs:element name="ProgEstudios">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="progreso" type="xs:string" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="DNIprofe" type="DNIType" use="required"/>
                        <xs:attribute name="ID" type="IDType" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cindy25-Collab/ByteMe/XML_Cursos/cursos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="cursos.xslt" type="text/xsl"?>

<cursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Cursos.xsd">

    <curso DNIprofe="15928473R" ID="101">
        <Horario>12:30</Horario>
        <idioma>Euskera</idioma>
        <NivelDificultad>Básico</NivelDificultad>
        <ProgEstudios progreso="creditos">100</ProgEstudios>
    </curso>

    <curso DNIprofe="48736291M" ID="25">
        <Horario>15:30</Horario>
        <idioma>Español</idioma>
        <NivelDificultad>Intermedio</NivelDificultad>
        <ProgEstudios progreso="creditos">50</ProgEstudios>
    </curso>

    <curso DNIprofe="90217463A" ID="7">
        <Horario>19:30</Horario>
        <idioma>Inglés</idioma>
        <NivelDificultad>Avanzado</NivelDificultad>
        <ProgEstudios progreso="creditos">75</ProgEstudios>
    </curso>

    <curso DNIprofe="36182947Z" ID="300">
        <Horario>14:30</Horario>
        <idioma>Euskera</idioma>
        <NivelDificultad>Intermedio</NivelDificultad>
        <ProgEstudios progreso="creditos">20</ProgEstudios>
    </curso>

    <curso DNIprofe="74829165H" ID="1">
        <Horario>20:30</Horario>
        <idioma>Español</idioma>
        <NivelDificultad>Básico</NivelDificultad>
        <ProgEstudios progreso="creditos">10</ProgEstudios>
    </curso>

</cursos>
